version: "3.7"

services:
  stacks:
    image: blockstack/stacks-blockchain
    restart: on-failure
    stop_grace_period: 1m
    command: /bin/stacks-node start --config /src/stacks-node/Config.toml
    volumes:
      - "./stacks-blockchain/persistent-data/stacks-blockchain/mainnet:/root/stacks-node/data"
      - "./stacks-blockchain/config/mainnet:/src/stacks-node"
    ports:
      - 20443:20443
      - 20444:20444
